### ISSUE TITLE
JsonParser throws NumberFormatException for input string: ""

### ISSUE THREAD

**Issue by liniu** [oblac/jodd#239] opened 2015-09-30 14:07 UTC
Hi,igorspasic, `JsonParser` throws `NumberFormatException` for input string: `""`, exception stack  as follows: 

```
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.valueOf(Integer.java:766)
	at jodd.typeconverter.impl.IntegerConverter.convert(IntegerConverter.java:41)
	at jodd.typeconverter.impl.IntegerConverter.convert(IntegerConverter.java:19)
	at jodd.typeconverter.TypeConverterManagerBean.convertType(TypeConverterManagerBean.java:283)
	at jodd.typeconverter.TypeConverterManager.convertType(TypeConverterManager.java:60)
	at jodd.json.JsonParserBase.convertType(JsonParserBase.java:108)
	at jodd.json.JsonParser.parseValue(JsonParser.java:287)
	at jodd.json.JsonParser.parseObjectContent(JsonParser.java:808)
	at jodd.json.JsonParser.parseValue(JsonParser.java:293)
	at jodd.json.JsonParser._parse(JsonParser.java:233)
	at jodd.json.JsonParser.parse(JsonParser.java:194)
```

and sources as follows: 
```
String src = "{\"intVar\":\"\",\"strVar\":\"\"}";
JsonParser parser = new JsonParser();
Bean bean = parser.parse(src, Bean.class);

public class Bean
{
Integer intVar;
String strVar;
//...
}
```
is this a bug ?

**Comment by zqq90** [comment] 2015-09-30 14:20
Obviously not
Something framworks should do, something not
Ample food and clothing by working with our own hands.
~~~~~
Jodd 的扩展性很好,  不明白可以加Q群 250805369 
                                                     -- from Beijing 
~~~~~

**Comment by igorspasic** [comment] 2015-10-03 17:30
In Jodd's world, this is not a bug :) Here is why:

`JsonParser` reads the value from the JSON string, and the values is empty string. Parsing itself work. However, converting the _empty_ string into the `Integer` (so to be injected into the `Bean#intVar`) is what is failing.

What you experience is basically the same as: `Integer.valueOf("")`.

I hope this helped :) I will close this issue; let me know if this is ok with you!

**Closed by igorspasic** 2015-10-03 17:30 UTC
Labels: invalid

**Comment by liniu** [comment] 2015-10-05 01:24
thanks
