### ISSUE TITLE
I encountered a problem

### ISSUE THREAD

**Issue by zhangxiangfeng** [oblac/jodd#564] opened 2018-01-25 12:36 UTC
Idea IDE compile is error

In Class  `MailServer.Builder`  Why  not public ?

**Comment by slandelle** [comment] 2018-01-25 12:39
Duplicate of #561

**Comment by zhangxiangfeng** [comment] 2018-01-25 12:52
ok
@slandelle

**Comment by zhangxiangfeng** [comment] 2018-01-25 12:52
i used 3.9.1 is ok

**Comment by igr** [comment] 2018-01-25 22:10
Sorry about that! Releasing new version now!

**Closed by igr** 2018-01-25 22:10 UTC
Labels: duplicate

**Comment by igr** [comment] 2018-01-26 01:54
@zhangxiangfeng 4.1.1. released!!!

**Comment by zhangxiangfeng** [comment] 2018-02-02 04:09
ok
