### ISSUE TITLE
jodd-props not support map

### ISSUE THREAD

**Issue by cn-src** [oblac/jodd#610] opened 2018-05-25 17:20 UTC
## Current behavior
jodd-props not support like this config:
```
map[key]=value
```

## Expected behavior
I want to use it with jodd-bean to finish parse to javabean.

Or is there another easy way to parse a configuration file into a javabean?

**Comment by igr** [comment] 2018-05-25 18:44
Hey @cn-src! There are already few ways how you can do that. Check out the: 

https://github.com/oblac/jodd/blob/master/jodd-props/src/test/java/jodd/props/PropsBeanTest.java

So, to summarize:

1. convert to `Map` and then simply `BeanCopy` it.

Props:
```
http.port=10101
http.address=localhost
http.pool=30
foo=bar
```
Code:
```java
Map innerMap = props.innerMap("http");
HttpConfig httpConfig = new HttpConfig();
BeanCopy.fromMap(innerMap).toBean(httpConfig).copy();
```

2. iterate all entries and inject however you want.

Props:
```
port=10101
address=localhost
pool=30
foo=bar
```
Code:
```
final HttpConfig httpConfig = new HttpConfig();

props.entries().forEach(
    pe -> BeanUtil.silent.setProperty(httpConfig, pe.getKey(), pe.getValue()));
```

(note: I use here `forEach` that I just comitted, nevertheless, you can use `iterator()` until the new release in similar fashion.

Hope this helps !

**Comment by cn-src** [comment] 2018-05-25 19:11
Code:
```java
Props props = new Props();
props.load("map[k1]=v1");
System.out.println(props.entries().iterator().next().getKey());
```
The code print "k1", not "map[k1]".

I expect to use it like this:
```java
BeanUtil.pojo.setProperty(cbean, "arr[4].map[elem.boo].foo", "test");
```

**Comment by igr** [comment] 2018-05-25 19:29
Ah, yes, the issue is the following:

In `Props` the `[]` are marking the [sections](https://jodd.org/props/#sections). So, your example is basically rendered like this:

```
map
[k1]=v1
```
and that`s why you have just a single entry of `k1`.

You can fix this by _escaping_ the first `[`:

```java
props.load("map\\[k1]=v1");
```

I know, it's not nice, so I will make a fix that only when `[` is the first character of the line it is a section, otherwise, it is a common character.

Sorry for this little inconvenience!

**Comment by igr** [comment] 2018-05-25 19:40
Just committed the fix.

It should be compatible with your version of Jodd, if you don't want to wait for v5 :)

**Closed** 2018-05-25 19:39 UTC
Labels: docs, howto, jodd-props

**Comment by cn-src** [comment] 2018-05-25 19:48
Thank you, looking forward to the new release.
