### ISSUE TITLE
HttpBase<T>.populateHeaderAndBody should not modify header key capitalization

### ISSUE THREAD

**Issue by brandon8863** [oblac/jodd#424] opened 2017-08-22 21:11 UTC
Using a web service that actually has case sensitive keys so it is not recognizing the credentials set in the header and sends back a 401 status.

**Comment by neroux** [comment] 2017-08-23 19:34
[HTTP headers are case insensitive](https://tools.ietf.org/html/rfc7230#section-3.2), so the proper fix would be within that service.

That kind of answer might not be exactly what you are after though :). From what I can tell the issue is Jodd manages the headers internally for comparison reasons in [lower case](https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/HttpBase.java#L143) and only [capitalises them upon the output](https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/HttpUtil.java#L133).

Changing that might be a bigger task .... if there werent already some [case insensitive support in the backing hashtable](https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/HttpBase.java#L75) :). Considering that already seems to be in place it might be enough to remove the toLowerCase() calls and the capitalisation. Maybe @igr can shed more light here :) though that service should still be fixed.

**Comment by brandon8863** [comment] 2017-08-23 19:49
I agree with you completely on the case sensitivity from the web service. Unfortunately it's a 3rd party B2B integration that is unlikely to get updated to spec.

It's not a huge show stopper for us. Worse case scenario we could inherit from HttpBase and override that method (and any other related issues) since it's protected.

If I were to put together a pull request would you prefer a boolean property on HttpBase that defaults to the current behavior?

**Comment by igr** [comment] 2017-08-23 19:54
Hi @brandon8863!

Let's see how we can fix this... As @neroux explained well: we need to have
default behavior (case-insensitive) as this is what RFC protocol specifies:

> Each header field consists of a name followed by a colon (":") and the
field value. Field names are case-insensitive.

However, I believe we can add a flag for your usecase - that would be set
either once globally, or every time when creating one of the request and
response. Would this approach work for you? The fix would be around the map
that stores the data, we have both versions (case sensitive and case
insensitive). But there are some `toLowerCase` that we need to check as
well.

Or - just thinking out loud here - we can have a 'special' headers, so
instead of using `header()` for adding it, you would use e.g.:
`headerSensitive()` (ok, we need better name :).

wdyt?

**Comment by neroux** [comment] 2017-08-23 20:07
@brandon8863 Could you try to modify HttpBase according to the steps previously mentioned steps and check whether that might work?

@igr Is there really a flag necessary? The hashtable already seems to support it, so skipping the lower case should do the trick, shouldnt it?

**Comment by igr** [comment] 2017-08-23 20:39
@neroux true, just have to double check...


For example, i would be happy with the following :

+ header are stored as provided, unmodified
+ however, headers are still case insensitive.

So if you add `Foo` header it would appear as that, but checking for `foo`
would return the same result as for `Foo`.

P.s. Im out of home until weekend so please don't mind my late response



--
Kind regards,
Igor

-= *Jodd* =-
lightweight java library
and micro frameworks
jodd.org

**Comment by neroux** [comment] 2017-08-23 20:42
> So if you add `Foo` header it would appear as that, but checking for `foo` would return the same result as for `Foo`.

But isnt that exactly the logic HttpMultiMap already follows with `caseSensitive` set to `false`?

**Comment by brandon8863** [comment] 2017-08-23 20:43
@igr Agreed, that was the default behavior I was expecting.

I only mentioned the flag approach to cover the edge case where there's someone out there passing in all lowercase keys and the service they are hitting is case sensitive and expecting the current upper first letter behavior. Probably not an actual case, but we are talking about a case sensitive service I'm hitting, so who knows what's out in the wild :)

**Comment by igr** [comment] 2017-08-23 20:46
Good question - i remember now something was different. Let me check again,
but not sure if i can push on this wifi ;(

--
Kind regards,
Igor

-= *Jodd* =-
lightweight java library
and micro frameworks
jodd.org

**Comment by neroux** [comment] 2017-08-24 15:25
No worries, whenever you find time. I am not sure either that it would work, it is just an impression based on my limited understanding of HttpMultiMap :)

@brandon8863 The edge case, respectively backwards compatibility, is a good point. In that case HttpBase might want to have such a flag, [indicating whether headers should be rewritten or not](https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/HttpBase.java#L780).

**Comment by igr** [comment] 2017-08-28 00:13
Closed by #425

**Closed by igr** 2017-08-28 00:13 UTC
