### ISSUE TITLE
StringIndexOutOfBoundsException when using MethRef

### ISSUE THREAD

**Issue by tlxtellef** [oblac/jodd#491] opened 2017-11-10 08:40 UTC
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at jodd.asm5.Frame.execute(Frame.java:1361)
	at jodd.asm5.MethodWriter.visitTypeInsn(MethodWriter.java:855)
	at jodd.proxetta.asm.ProxettaAsmUtil.castToReturnType(ProxettaAsmUtil.java:553)
	at jodd.proxetta.asm.ProxettaMethodBuilder$1$1.visitMethodInsn(ProxettaMethodBuilder.java:375)
	at jodd.asm5.ClassReader.readCode(ClassReader.java:1496)
	at jodd.asm5.ClassReader.readMethod(ClassReader.java:1032)
	at jodd.asm5.ClassReader.accept(ClassReader.java:708)
	at jodd.asm5.ClassReader.accept(ClassReader.java:521)
	at jodd.proxetta.asm.ProxettaMethodBuilder.createProxyMethod(ProxettaMethodBuilder.java:185)
	at jodd.proxetta.asm.ProxettaMethodBuilder.visitEnd(ProxettaMethodBuilder.java:103)
	at jodd.asm5.ClassReader.readMethod(ClassReader.java:1036)
	at jodd.asm5.ClassReader.accept(ClassReader.java:708)
	at jodd.asm5.ClassReader.accept(ClassReader.java:521)
	at jodd.proxetta.impl.ProxyProxettaBuilder.process(ProxyProxettaBuilder.java:76)
	at jodd.proxetta.ProxettaBuilder.process(ProxettaBuilder.java:220)
	at jodd.proxetta.ProxettaBuilder.define(ProxettaBuilder.java:255)
	at jodd.methref.MethrefProxetta.defineProxy(MethrefProxetta.java:56)
	at jodd.methref.Methref.<init>(Methref.java:57)
	at jodd.methref.Methref.on(Methref.java:79)

Version: 3.9.1
I should probably mention that AspectJ with postcompile weave is in use.

**Comment by igr** [comment] 2017-11-10 15:43
Hey @tlxtellef! Any chance to get the class so I can try to repeat? From the stacktrace I see the issue is somewhere in ASM library - of course, probably because I did something wrong.

Or can you share the method signature for the method you used MethRef onto?

**Comment by igr** [comment] 2017-11-12 10:43
Any hints on how I can reproduce this @tlxtellef ?

**Comment by tlxtellef** [comment] 2017-11-12 17:49
@igr Sorry for the delay. I will get back to you when I can reproduce this bug with new code (as I did with #418). The method signature is something like this `public static int getFoo(int a, int b)`. I think it is probably some other unusual construct in the codebase.

**Comment by igr** [comment] 2017-11-12 20:53
Thanx @tlxtellef ! I will try to reproduce meanwhile, maybe `static` was failing for some reason.

**Comment by igr** [comment] 2018-01-13 00:42
The #555 might be related. Closing this one, hopefully, it is fixed.

**Closed by igr** 2018-01-13 00:42 UTC
Labels: bug, jodd-proxetta
